title: Tvheadend.org
description: >-
  Tvheadend is the leading TV streaming server for Linux supporting ATSC, DVB-C,<br>
  DVB-S/S2, DVB-T/T2, ISDB-T, IPTV, SAT>IP and HDHomeRun sources
logo: images/logo-clear-200px.png

address: 1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA
phone: (000) 000-0000 x 0000
email: team@tvheadend.org

socials:
  GitHub: "https://github.com/tvheadend/tvheadend"
  OpenCollective: "https://opencollective.com/tvheadend"
